services:
  - type: web
    name: bling-updater-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: PORT
        value: 10000
